-- ============================================================================
-- Serverless Projects Hub — PostgreSQL schema (Neon / any Postgres ≥ 14)
-- ============================================================================
-- Run with:
--   psql "$DATABASE_URL" -f database/schema.sql
-- or paste into the Neon SQL editor / Vercel Postgres query tab.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ----------------------------------------------------------------------------
-- projects
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
  id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),

  title         VARCHAR(100) NOT NULL,
  url           TEXT         NOT NULL,
  description   VARCHAR(500) NOT NULL,

  author_name   VARCHAR(80)  NOT NULL,
  author_bio    VARCHAR(500),
  -- Contact email is optional and NEVER exposed by the public API.
  contact_email VARCHAR(255),

  -- Public URL of the optimized image in Vercel Blob (or NULL → default SVG).
  image_url     TEXT,

  status        VARCHAR(20)  NOT NULL DEFAULT 'published'
                  CHECK (status IN ('published', 'hidden', 'pending', 'blocked')),

  -- Marks rows inserted by the seed script so they can be removed easily.
  is_seed       BOOLEAN      NOT NULL DEFAULT FALSE,

  -- Reserved for future expansion (categories, tags, favorites, ...).
  -- category    VARCHAR(40),
  -- tags        TEXT[],

  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- ratings
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ratings (
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),

  project_id  UUID         NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  -- Anonymous client identifier generated by the browser (localStorage).
  -- One rating per (project_id, visitor_id); visitors may update their vote.
  visitor_id  VARCHAR(100) NOT NULL,

  rating      SMALLINT     NOT NULL CHECK (rating >= 1 AND rating <= 5),

  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_rating_per_visitor UNIQUE (project_id, visitor_id)
);

-- ----------------------------------------------------------------------------
-- Indexes
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_projects_created_at
  ON projects (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_projects_status
  ON projects (status);

CREATE INDEX IF NOT EXISTS idx_projects_search
  ON projects USING gin (
    to_tsvector('english', title || ' ' || description || ' ' || author_name)
  );

CREATE INDEX IF NOT EXISTS idx_ratings_project_id
  ON ratings (project_id);

CREATE INDEX IF NOT EXISTS idx_ratings_visitor
  ON ratings (project_id, visitor_id);

-- ----------------------------------------------------------------------------
-- updated_at maintenance
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_projects_updated_at ON projects;
CREATE TRIGGER trg_projects_updated_at
  BEFORE UPDATE ON projects
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_ratings_updated_at ON ratings;
CREATE TRIGGER trg_ratings_updated_at
  BEFORE UPDATE ON ratings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
